# 串口设备号
device: "/dev/gps_serial"
# 串口波特率
baud_rate: 115200
# 投影参数 (UTM Zone 50 适用于北京/西安区域)
proj4_text: "+proj=utm +zone=50 +ellps=WGS84"

#是否使用固定点作为平面坐标原点
use_fixed_origin: true
# Beijing Forbidden City
origin_lat: 39.918058
origin_lon: 116.397026
origin_alt: 45.0
