load("//tools/proto:proto.bzl", "proto_library")
load("//tools:apollo_package.bzl", "apollo_package")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "cilqr_planner_conf_proto",
    srcs = ["cilqr_planner_conf.proto"],
)

apollo_package()
