# Copyright 2023 The Apollo Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Auto generated by buildtool of apollo

STATUS = 2

SOURCE = {
    "common-msgs" : {
        "path": "//modules/common_msgs",
        "depends": [
            "3rd-protobuf",
            
        ],
    },
    "cyber" : {
        "path": "//cyber",
        "depends": [
            "3rd-eigen3",
            "3rd-fastdds-wrap",
            "3rd-gflags",
            "3rd-glog",
            "3rd-gtest",
            "3rd-nlohmann-json",
            "3rd-proj",
            "3rd-protobuf",
            "bvar",
            "gperftools",
            "libncurses5-dev",
            "libtinyxml2-dev",
            "libunwind-dev",
            "nethogs",
            "sysstat",
            "uuid-dev",
            
        ],
    },
    "cilqr-planner" : {
        "path": "//modules/planning/cilqr_planner",
        "depends": [
            "3rd-eigen3",
            "3rd-fastdds-wrap",
            "3rd-gflags",
            "3rd-glog",
            "3rd-gtest",
            "3rd-nlohmann-json",
            "3rd-opencv",
            "3rd-proj",
            "3rd-protobuf",
            "bvar",
            "gperftools",
            "libgtk2.0-0",
            "libncurses5-dev",
            "libtinyxml2-dev",
            "libunwind-dev",
            "libwebp-dev",
            "nethogs",
            "sysstat",
            "uuid-dev",
            
        ],
    },
    
}

BINARY = {
    "bazel-extend-tools" : {
        "path": "//tools",
        "targets": [
            
        ],
    },
    "3rd-protobuf" : {
        "path": "//third_party/protobuf",
        "targets": [
            "@com_google_protobuf//:protobuf",
            
        ],
    },
    "libncurses5-dev" : {
        "path": "None",
        "targets": [
            "@ncurses5//:ncurses5",
            
        ],
    },
    "uuid-dev" : {
        "path": "None",
        "targets": [
            "@uuid//:uuid",
            
        ],
    },
    "3rd-fastdds-wrap" : {
        "path": "//third_party/fastrtps_wrap",
        "targets": [
            "@fastdds//:fastdds",
            
        ],
    },
    "3rd-proj" : {
        "path": "//third_party/proj",
        "targets": [
            "@proj//:proj",
            
        ],
    },
    "3rd-eigen3" : {
        "path": "//third_party/eigen3",
        "targets": [
            "@eigen//:eigen",
            
        ],
    },
    "3rd-glog" : {
        "path": "//third_party/glog",
        "targets": [
            "@com_github_google_glog//:glog",
            
        ],
    },
    "3rd-gflags" : {
        "path": "//third_party/gflags",
        "targets": [
            "@com_github_gflags_gflags//:gflags",
            
        ],
    },
    "3rd-gtest" : {
        "path": "//third_party/gtest",
        "targets": [
            "@com_google_googletest//:gtest",
            "@com_google_googletest//:gtest_main",
            
        ],
    },
    "3rd-nlohmann-json" : {
        "path": "//third_party/nlohmann_json",
        "targets": [
            "@com_github_nlohmann_json//:json",
            "@com_github_nlohmann_json//:single_json",
            
        ],
    },
    "libtinyxml2-dev" : {
        "path": "None",
        "targets": [
            "@tinyxml2//:tinyxml2",
            
        ],
    },
    "libunwind-dev" : {
        "path": "None",
        "targets": [
            "@libunwind-dev//:libunwind-dev",
            
        ],
    },
    "nethogs" : {
        "path": "None",
        "targets": [
            "@nethogs//:nethogs",
            
        ],
    },
    "sysstat" : {
        "path": "None",
        "targets": [
            "@sysstat//:sysstat",
            
        ],
    },
    "gperftools" : {
        "path": "None",
        "targets": [
            "@gperftools//:gperftools",
            
        ],
    },
    "bvar" : {
        "path": "None",
        "targets": [
            "@bvar//:bvar",
            
        ],
    },
    "3rd-opencv" : {
        "path": "//third_party/opencv",
        "targets": [
            "@opencv//:core",
            "@opencv//:highgui",
            "@opencv//:imgcodecs",
            "@opencv//:imgproc",
            
        ],
    },
    "libgtk2.0-0" : {
        "path": "None",
        "targets": [
            "@libgtk2.0-0//:libgtk2.0-0",
            
        ],
    },
    "libwebp-dev" : {
        "path": "None",
        "targets": [
            "@libwebp-dev//:libwebp-dev",
            
        ],
    },
    
}