
load("//tools/install:install.bzl", "install", "install_src_files")

package(
    default_visibility = ["//visibility:public"],
)


install(
    name = "mock_install",
    type = "neo",
    deps = ["//third_party/tf2:install","//third_party/can_card_library:install","//modules/common_msgs:install","//cyber:install","//modules/common:install","//modules/transform:install","//third_party/rtklib:install","//third_party/camera_library:install","//modules/drivers/canbus:install","//modules/canbus:install","//modules/canbus_vehicle/ge3:install","//modules/canbus_vehicle/demo:install","//modules/canbus_vehicle/neolix_edu:install","//modules/canbus_vehicle/gem:install","//modules/canbus_vehicle/wey:install","//modules/canbus_vehicle/transit:install","//modules/canbus_vehicle/mycar:install","//modules/canbus_vehicle/articulated:install","//modules/canbus_vehicle/lincoln:install","//modules/canbus_vehicle/lexus:install","//modules/canbus_vehicle/devkit:install","//modules/canbus_vehicle/ch:install","//modules/canbus_vehicle/zhongyun:install"],
)


install_src_files(
    name = "mock_install_src",
    type = "neo",
    deps = ["//third_party/tf2:install_src","//third_party/can_card_library:install_src","//modules/common_msgs:install_src","//cyber:install_src","//modules/common:install_src","//modules/transform:install_src","//third_party/rtklib:install_src","//third_party/camera_library:install_src","//modules/drivers/canbus:install_src","//modules/canbus:install_src","//modules/canbus_vehicle/ge3:install_src","//modules/canbus_vehicle/demo:install_src","//modules/canbus_vehicle/neolix_edu:install_src","//modules/canbus_vehicle/gem:install_src","//modules/canbus_vehicle/wey:install_src","//modules/canbus_vehicle/transit:install_src","//modules/canbus_vehicle/mycar:install_src","//modules/canbus_vehicle/articulated:install_src","//modules/canbus_vehicle/lincoln:install_src","//modules/canbus_vehicle/lexus:install_src","//modules/canbus_vehicle/devkit:install_src","//modules/canbus_vehicle/ch:install_src","//modules/canbus_vehicle/zhongyun:install_src"],
)
